<Project Sdk="Microsoft.NET.Sdk.Web">

	<Import Project="..\CM\Version\assemblyversion.props" />
	
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>Modulyn Server</Title>
    <PackageIcon>ModulynBlazor.jpg</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.14.0" />
    <PackageReference Include="Lumberjack" Version="0.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.16" />
    <PackageReference Include="System.Formats.Asn1" Version="9.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ModulynInterface\ModulynInterface.csproj" />
    <ProjectReference Include="..\ModulynServerBl\ModulynServerBl.csproj" />
  </ItemGroup>

</Project>
